import streamlit as st
import pandas as pd
import plotly.express as px
import io

# --- 1. THE CLEANING LOGIC (Internal Function) ---
def clean_data_strictly(df):
    # Fix Dates
    df['transaction_date'] = pd.to_datetime(df['transaction_date'], errors='coerce')
    df = df.dropna(subset=['transaction_date'])
    
    # Fix Price
    df['price'] = df['price'].astype(str).str.replace(r'[^\d.]', '', regex=True)
    df['price'] = pd.to_numeric(df['price'], errors='coerce').fillna(0)
    
    # Standardize Regions
    df['region'] = df['region'].str.strip().str.title()
    df['region'] = df['region'].replace({'N. Tech': 'North', 'S-Region': 'South'})
    
    # Deduplicate
    df = df.drop_duplicates()
    return df

# --- 2. THE UI ---
st.set_page_config(page_title="Auto-Clean Pro", layout="wide")
st.title("🚀 Instant Data Automation")

# File Uploader
uploaded_file = st.file_uploader("Upload your messy data", type=["csv"])

if uploaded_file is not None:
    # Read raw data
    try:
    # Try reading with standard UTF-8 first
         raw_df = pd.read_csv(uploaded_file)
    except UnicodeDecodeError:
    # If that fails, try 'latin1' (common for Excel/Windows-saved CSVs)
         uploaded_file.seek(0) # Reset file pointer to the start
         raw_df = pd.read_csv(uploaded_file, encoding='latin-1')
     
    # STRICTION CHECK: Verify headers match our demo
    required_cols = {'transaction_date', 'region', 'product_name', 'price'}
    if required_cols.issubset(raw_df.columns):
        
        # AUTOMATIC CLEANING
        with st.spinner('Automating cleaning logic...'):
            clean_df = clean_data_strictly(raw_df)
            st.success("Data Cleaned Successfully!")

        # DISPLAY METRICS
        c1, c2, c3 = st.columns(3)
        c1.metric("Total Revenue", f"${clean_df['price'].sum():,.2f}")
        c2.metric("Rows Processed", len(clean_df))
        c3.metric("Duplicates Removed", len(raw_df) - len(clean_df))

        # VISUALIZATION
        fig = px.bar(clean_df, x='region', y='price', color='product_name', title="Cleaned Sales Insight")
        st.plotly_chart(fig, use_container_width=True)

        # DOWNLOAD BUTTON
        csv_buffer = io.StringIO()
        clean_df.to_csv(csv_buffer, index=False)
        st.download_button(
            label="📩 Download Cleaned CSV",
            data=csv_buffer.getvalue(),
            file_name="cleaned_data_export.csv",
            mime="text/csv",
        )
    else:
        st.error(f"Invalid Format! Please upload a CSV with these columns: {required_cols}")
else:

    st.info("Please upload the CSV file generated by your script to see the automation in action.")
